##### Here add the use specific information which are then loaded into the scripts, so you don't have to modify it in the single scripts


#User-defined Species File
input_path="00_input"
input_table= "Formated_species_list.csv"

# Algaebase login data
key="abapikey"
password="DgG70kVljer4ZgvjfVn6KFPK7bnuzKR6"

# email adress for NCBI
Entrez_email = "juliane.romahn@senckenberg.de"